let permissionData=[{
    title:"应用",
    children:[
        {
            title:"档案管理",
            children: [
                {
                    title:"录入档案",
                },
                {
                    title:"导入档案",
                },
                {
                    title:"导出档案",
                },
                {
                    title:"查询档案",
                },
                {
                    title:"打印档案",
                },
            ]
        },
        {
            title:"字段管理",
            children:[
                {
                    title:"客户类型",
                    children:[
                        {
                            title:"查找字段值",
                        },
                        {
                            title:"添加字段值",
                        },
                        {
                            title:"编辑字段值",
                        },
                        {
                            title:"删除字段值",
                        },
                    ]
                },
                {
                    title:"相关业务",
                    children:[
                        {
                            title:"查找字段值",
                        },
                        {
                            title:"添加字段值",
                        },
                        {
                            title:"编辑字段值",
                        },
                        {
                            title:"删除字段值",
                        },
                    ]
                },{
                    title:"现用软件品牌",
                    children:[
                        {
                            title:"查找字段值",
                        },
                        {
                            title:"添加字段值",
                        },
                        {
                            title:"编辑字段值",
                        },
                        {
                            title:"删除字段值",
                        },
                    ]
                },{
                    title:"信息来源",
                    children:[
                        {
                            title:"查找字段值",
                        },
                        {
                            title:"添加字段值",
                        },
                        {
                            title:"编辑字段值",
                        },
                        {
                            title:"删除字段值",
                        },
                    ]
                },
            ]
        },
        {
            title:"用户权限",
            children:[
                {
                    title:"用户管理",
                    children:[
                        {
                            title:"查找",
                        },
                        {
                            title:"添加",
                        },
                        {
                            title:"编辑",
                        },
                        {
                            title:"删除",
                        },
                    ]
                },
                {
                    title:"角色管理",
                    children:[
                        {
                            title:"添加",
                        },
                        {
                            title:"编辑",
                        },
                        {
                            title:"删除",
                        },
                    ]
                },
                {
                    title:"查看权限列表",
                },
            ]
        },
        {
            title:"统计分析",
            children:[
                {
                    title:"查看各阶段客户数量",
                },
                {
                    title:"查看每年/季度/月新增客户数量",
                },
                {
                    title:"查看客户构成",
                },

            ]
        },
        {
            title:"销售人员信息管理",
            children:[
                {
                    title:"查找",
                },
                {
                    title:"添加",
                },
                {
                    title:"编辑",
                },
                {
                    title:"删除",
                },
            ]
        },
        {
            title:"系统安全",
            children:[
                {
                    title:"数据备份与恢复",
                },
                {
                    title:"安全设置",
                },
            ]
        },
    ]
}];